metadata:
  name: cats
  namespace: cats
  labels:
    course: clo835
    week: week5
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cats-pod
  template:
    metadata:
      labels:
        name: cats-pod
    spec:
      containers:
      - name: cats-container
        image: 181212752313.dkr.ecr.us-east-1.amazonaws.com/mid-term:catsv1.0
        # httpd:2.4-alpine