---
kind: Namespace
apiVersion: v1
metadata:
  name: dogs
  labels:
    name: dogs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs
  namespace: dogs
  labels:
    course: clo835
    assignment: assignment-2
spec:
  replicas: 0
  selector:
    matchLabels:
      name: dogs
  template:
    metadata:
      labels:
        name: dogs
    spec:
      containers:
      - name: dogs
        image: 181212752313.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:dogs