kind: Namespace
apiVersion: v1
metadata:
  name: dogs
  labels:
    name: dogs
---
apiVersion: v1
kind: Service
metadata:
  name: dogs
  labels:
    course: clo835
    assignment: assignment-2
    app: dogs
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - port: 80
    targetPort:
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30001
  selector:
      course: clo835
      assignment: assignment-2
      app: dogs
    